# Welcome to Jekyll!
# set JEKYLL_ENV=production | bundle exec jekyll build

title: Lo que Sea
email: <a href:"mailto:loqueseafoodtruck21@gmail.com">loqueseafoodtruck21@gmail.com</a>
phone: +52 1 661 128 6663
description: >- # this means to ignore newlines until "baseurl:"
  Â¡Lo Que Sea Food Truck Italian Deli Rosarito! We are here to serve, Breakfast, Sandwiches, Drinks, and Desserts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loquesearosarito.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

social:
  name: Lo que Sea
  links:
facebook: https://www.facebook.com/loquesearosarito/
instagram: https://www.instagram.com/loquesea.foodtruck/
twitter: https://twitter.com/CentroRosarito
linkedin: https://www.linkedin.com/in/rosaritocentro/
youtube: https://www.youtube.com/channel/UCWexmtM12ZHXjHvuQAxeXsQ

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap

twitter:
  username: CentroRosarito
  card: summary

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      lazy: true
      image:
        path: img/og-image.png
        height: 512
        width: 512
      author: Rosarito Centro   
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
